### ISSUE TITLE
Explore index of multiple deprivation data

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/heat_pump_adoption_modelling#9]
[Some Notes about IMD](https://docs.google.com/document/d/1juwDmIBhXCrml6-C1yF8qd2vyRXeaE93lJPwO_IxjX0/edit?usp=sharing)

- [x] What the composite index is made of
- [x] Whether individual components are more useful than the overall index
- [x] Check whether the score is available instead of the rank

**Comment by athrado** [comment]
**Conclusion**

- Ranks and deciles not so useful for us
- Scores only meaningful for Income and Employment Deprivation (percentage of population)
- Income and Employment Deprivation seem to be computed very similarly for England, Wales, Scotland and even Northern Ireland
- Indices and Scores available for all countries
- Postcodes maps available for LSOA
